# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Naorf\Documents\GitHub\Trivia-Game\src\Python-code\Home\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 600)
        Form.setStyleSheet("QWidget{\n"
"background-color: rgb(54, 54, 54);\n"
"}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(230, 130, 381, 101))
        self.label.setStyleSheet("font: 46pt \"Consolas\";\n"
"color: rgb(255, 255, 127);")
        self.label.setObjectName("label")
        self.playbutton = QtWidgets.QPushButton(Form)
        self.playbutton.setGeometry(QtCore.QRect(280, 270, 261, 41))
        self.playbutton.setStyleSheet("font: 26pt \"Consolas\";\n"
"color: rgb(255, 255, 0);\n"
"letter-spacing:2px;")
        self.playbutton.setObjectName("playbutton")
        self.scoretablbutton = QtWidgets.QPushButton(Form)
        self.scoretablbutton.setGeometry(QtCore.QRect(280, 330, 261, 41))
        self.scoretablbutton.setStyleSheet("font: 26pt \"Consolas\";\n"
"color: rgb(255, 255, 0);\n"
"letter-spacing:2px;")
        self.scoretablbutton.setObjectName("scoretablbutton")
        self.menu = QtWidgets.QFrame(Form)
        self.menu.setGeometry(QtCore.QRect(680, 30, 101, 121))
        self.menu.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-radius:10px;\n"
"font: 10pt \"Consolas\";\n"
"color: rgb(255, 255, 0);\n"
"letter-spacing:1px;\n"
"border: 1px solid rgb(255, 255, 127);\n"
"out line:none;\n"
"}\n"
"\n"
"QFrame{\n"
"border: 1px solid rgb(255, 255, 198);\n"
"border-radius:15px;\n"
"}")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.profilebutton = QtWidgets.QPushButton(self.menu)
        self.profilebutton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.profilebutton.setStyleSheet("")
        self.profilebutton.setObjectName("profilebutton")
        self.settingbutton = QtWidgets.QPushButton(self.menu)
        self.settingbutton.setGeometry(QtCore.QRect(10, 90, 75, 23))
        self.settingbutton.setStyleSheet("")
        self.settingbutton.setObjectName("settingbutton")
        self.shopbutton = QtWidgets.QPushButton(self.menu)
        self.shopbutton.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.shopbutton.setStyleSheet("")
        self.shopbutton.setObjectName("shopbutton")
        self.menubutton = QtWidgets.QPushButton(Form)
        self.menubutton.setGeometry(QtCore.QRect(770, 20, 71, 51))
        self.menubutton.setStyleSheet("border-radius:10px;")
        self.menubutton.setObjectName("menubutton")
        self.menubutton.raise_()
        self.label.raise_()
        self.playbutton.raise_()
        self.scoretablbutton.raise_()
        self.menu.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Trivia Game"))
        self.playbutton.setText(_translate("Form", "Play Game"))
        self.scoretablbutton.setText(_translate("Form", "Score Table"))
        self.profilebutton.setText(_translate("Form", "profile"))
        self.settingbutton.setText(_translate("Form", "Settings"))
        self.shopbutton.setText(_translate("Form", "shop"))
        self.menubutton.setToolTip(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-size:7pt; font-weight:600; text-decoration: underline;\">__________</span></p><p align=\"justify\"><span style=\" font-size:7pt; font-weight:600; text-decoration: underline;\">__________</span></p><p align=\"justify\"><span style=\" font-size:7pt; font-weight:600; text-decoration: underline;\">__________</span></p></body></html>"))
        self.menubutton.setWhatsThis(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt; font-weight:600; text-decoration: underline;\">__________</span></p><p align=\"justify\"><span style=\" font-size:6pt; font-weight:600; text-decoration: underline;\">__________</span></p><p align=\"justify\"><span style=\" font-size:6pt; font-weight:600; text-decoration: underline;\">__________</span></p></body></html>"))
        self.menubutton.setText(_translate("Form", "_____\n"
"_____\n"
"_____"))
import shop_rc
import user_rc
