# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Naorf\Documents\GitHub\Trivia-Game\src\Python-code\Login\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(450, 500)
        Login.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(190, 60, 71, 41))
        self.label.setStyleSheet("color: rgb(223, 223, 223);\n"
"font-size:28px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setGeometry(QtCore.QRect(40, 190, 51, 31))
        self.label_2.setStyleSheet("font-size:20px;\n"
"color: rgb(255, 170, 0);")
        self.label_2.setObjectName("label_2")
        self.email = QtWidgets.QLineEdit(Login)
        self.email.setGeometry(QtCore.QRect(140, 190, 220, 33))
        self.email.setStyleSheet("padding:5px;\n"
"border:2px solid rgb(26, 26, 26);\n"
"border-radius:15px;\n"
"font-size:15px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(117, 117, 117);")
        self.email.setObjectName("email")
        self.label_3 = QtWidgets.QLabel(Login)
        self.label_3.setGeometry(QtCore.QRect(28, 261, 81, 31))
        self.label_3.setStyleSheet("font-size:20px;\n"
"color: rgb(255, 170, 0);")
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QLineEdit(Login)
        self.password.setGeometry(QtCore.QRect(140, 260, 220, 33))
        self.password.setStyleSheet("padding:5px;\n"
"background-color: rgb(117, 117, 117);\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid rgb(26, 26, 26);\n"
"border-radius:15px;\n"
"font-size:15px;")
        self.password.setObjectName("password")
        self.loginbutton = QtWidgets.QPushButton(Login)
        self.loginbutton.setGeometry(QtCore.QRect(150, 380, 150, 35))
        self.loginbutton.setStyleSheet("padding:5px;\n"
"border:2px solid rgb(26, 26, 26);\n"
"border-radius:15px;\n"
"font-size:17px;\n"
"background-color: rgb(255, 204, 0);")
        self.loginbutton.setObjectName("loginbutton")
        self.createaccountbutton = QtWidgets.QPushButton(Login)
        self.createaccountbutton.setGeometry(QtCore.QRect(130, 420, 181, 23))
        self.createaccountbutton.setStyleSheet("color: rgb(254, 204, 0);\n"
"border:none;\n"
"")
        self.createaccountbutton.setObjectName("createaccountbutton")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label.setText(_translate("Login", "Login"))
        self.label_2.setText(_translate("Login", "Email:"))
        self.label_3.setText(_translate("Login", "Pasword"))
        self.loginbutton.setText(_translate("Login", "Login"))
        self.createaccountbutton.setText(_translate("Login", "Don\'t have an account? Create one"))
