# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Naorf\Documents\GitHub\Trivia-Game\src\Python-code\Profile\profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 600)
        Form.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"outline:none;")
        self.user_info_frame = QtWidgets.QFrame(Form)
        self.user_info_frame.setGeometry(QtCore.QRect(10, 10, 331, 81))
        self.user_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_info_frame.setObjectName("user_info_frame")
        self.Username_label = QtWidgets.QLabel(self.user_info_frame)
        self.Username_label.setGeometry(QtCore.QRect(70, 10, 151, 21))
        self.Username_label.setStyleSheet("font: 16pt \"Calibri\";\n"
"color: rgb(161, 161, 161);\n"
" letter-spacing: 1px;\n"
"")
        self.Username_label.setObjectName("Username_label")
        self.profile_logo = QtWidgets.QLabel(self.user_info_frame)
        self.profile_logo.setGeometry(QtCore.QRect(0, 0, 61, 61))
        self.profile_logo.setStyleSheet("")
        self.profile_logo.setText("")
        self.profile_logo.setPixmap(QtGui.QPixmap("c:\\Users\\Naorf\\Documents\\GitHub\\Trivia-Game\\src\\Python-code\\Profile\\../icons/user-icon.png"))
        self.profile_logo.setObjectName("profile_logo")
        self.uid_label = QtWidgets.QLabel(self.user_info_frame)
        self.uid_label.setGeometry(QtCore.QRect(70, 40, 91, 16))
        self.uid_label.setStyleSheet("font: 9pt \"Calibri\";\n"
"color: rgb(161, 161, 161);\n"
" letter-spacing: 0.5px;\n"
"")
        self.uid_label.setObjectName("uid_label")
        self.label = QtWidgets.QLabel(self.user_info_frame)
        self.label.setGeometry(QtCore.QRect(240, 0, 71, 71))
        self.label.setStyleSheet("border:10px;\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\Naorf\\Documents\\GitHub\\Trivia-Game\\src\\Python-code\\Profile\\../icons/coin.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.user_info_frame)
        self.label_2.setGeometry(QtCore.QRect(280, 60, 16, 16))
        self.label_2.setStyleSheet("font: 20pt \"Calibri\";\n"
"border-radius:5px;")
        self.label_2.setObjectName("label_2")
        self.add_coins_button = QtWidgets.QPushButton(self.user_info_frame)
        self.add_coins_button.setGeometry(QtCore.QRect(230, 0, 101, 81))
        self.add_coins_button.setStyleSheet("border:none;\n"
"background:none;")
        self.add_coins_button.setText("")
        self.add_coins_button.setObjectName("add_coins_button")
        self.label.raise_()
        self.Username_label.raise_()
        self.profile_logo.raise_()
        self.uid_label.raise_()
        self.label_2.raise_()
        self.add_coins_button.raise_()
        self.achievements_frame = QtWidgets.QFrame(Form)
        self.achievements_frame.setGeometry(QtCore.QRect(20, 110, 791, 161))
        self.achievements_frame.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.achievements_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.achievements_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.achievements_frame.setObjectName("achievements_frame")
        self.friends_frame = QtWidgets.QFrame(Form)
        self.friends_frame.setGeometry(QtCore.QRect(20, 280, 381, 311))
        self.friends_frame.setStyleSheet("background-color: rgb(19, 109, 255);")
        self.friends_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.friends_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.friends_frame.setObjectName("friends_frame")
        self.statistics_frame = QtWidgets.QFrame(Form)
        self.statistics_frame.setGeometry(QtCore.QRect(420, 280, 391, 311))
        self.statistics_frame.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.statistics_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statistics_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statistics_frame.setObjectName("statistics_frame")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Username_label.setText(_translate("Form", "Username"))
        self.uid_label.setText(_translate("Form", "UID - 22220001"))
        self.label_2.setText(_translate("Form", "+"))
import user_rc
